NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=
CLERK_SECRET_KEY=

NEXT_PUBLIC_CLERK_SIGN_IN_URL=/sign-in
NEXT_PUBLIC_CLERK_SIGN_UP_URL=/sign-up
NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL=/
NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL=/

DATABASE_URL="mysql://root:root@localhost:3306/lead-convert"
OPENAI_API_KEY=

UPLOADTHING_SECRET=
UPLOADTHING_APP_ID=

STRIPE_PRIVATE_API_KEY=
STRIPE_PUBLIC_API_KEY=